// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_PR3TsSp4ypZcB-FJxZkZLJzL2rmfUoo',
    appId: '1:87237846709:web:da2a72745f77c4f3c4c0fc',
    messagingSenderId: '87237846709',
    projectId: 'todo-service-8128f',
    authDomain: 'todo-service-8128f.firebaseapp.com',
    storageBucket: 'todo-service-8128f.appspot.com',
    measurementId: 'G-83WLXDK3JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSEDRhumiuWFSpyN14jMtYVw1T42Id7Cs',
    appId: '1:87237846709:android:8085d3ed015813c3c4c0fc',
    messagingSenderId: '87237846709',
    projectId: 'todo-service-8128f',
    storageBucket: 'todo-service-8128f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9-LpNMI4e07zWNavzJOaftXn35IFZyl8',
    appId: '1:87237846709:ios:1de1d9e2807a3101c4c0fc',
    messagingSenderId: '87237846709',
    projectId: 'todo-service-8128f',
    storageBucket: 'todo-service-8128f.appspot.com',
    iosClientId: '87237846709-l7997lkopa7qbdjqmh2kmo4ml00fklo0.apps.googleusercontent.com',
    iosBundleId: 'duy.lu.demo01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9-LpNMI4e07zWNavzJOaftXn35IFZyl8',
    appId: '1:87237846709:ios:1de1d9e2807a3101c4c0fc',
    messagingSenderId: '87237846709',
    projectId: 'todo-service-8128f',
    storageBucket: 'todo-service-8128f.appspot.com',
    iosClientId: '87237846709-l7997lkopa7qbdjqmh2kmo4ml00fklo0.apps.googleusercontent.com',
    iosBundleId: 'duy.lu.demo01',
  );
}
